
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 2;
const int acc_off_y = 4;
const int acc_off_z = -25;
const float acc_scale_x = 243.288664;
const float acc_scale_y = 307.509776;
const float acc_scale_z = 267.750743;

const int magn_off_x = -273;
const int magn_off_y = -78;
const int magn_off_z = 0;
const float magn_scale_x = 467.966032;
const float magn_scale_y = 459.795087;
const float magn_scale_z = 487.209495;
